/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Open a TUN device, returning the kernel fd. Linux only — fails
 * loudly on other platforms.
 */
export declare function openTun(name: string): number
/** Assign IPv4 + netmask (+ optional MTU) and bring the interface up. */
export declare function configureIf(name: string, ip: string, prefix: number, mtu?: number | undefined | null): void
/**
 * Close a TUN fd. No-op for `fd < 0`. Note: when the fd has been
 * handed off to `Tunnel.attachTun` or `TunGateway.attach`, the
 * lktunnel core owns the fd and the JS caller must NOT call
 * `close_tun` on it — let the owning handle clean up.
 */
export declare function closeTun(fd: number): void
/**
 * Toggle verbose per-flow NAT diagnostics in the Rust core. Affects
 * both kernel and userspace NAT paths: TCP retransmits / RTO / TLP
 * / cwnd / SACK events, UDP send/recv counters, fragment-buffer
 * expiry, throttle pauses. Hot-loop log sites are gated behind an
 * `AtomicBool`, so leaving this off costs effectively zero.
 */
export declare function setNatDebug(enabled: boolean): void
/**
 * JS-visible handle around `lktunnel::LkTunnel`. The Rust value is
 * owned through an `Arc` so the threadsafe-function callback (which
 * fires from `lktunnel`'s tokio worker) and JS-side method calls
 * share a stable lifetime regardless of which side drops last.
 */
export declare class Tunnel {
  /**
   * Build a handle and kick off the async connect work on the
   * shared lktunnel runtime. Non-blocking — events fire on
   * `on_event(kind, info)` as the connect task progresses.
   *
   * The `on_event` callback is invoked from the lktunnel tokio
   * worker thread; `ThreadsafeFunction` marshals it back onto the
   * Node event loop so JS code observes it like any other Node
   * callback.
   */
  static connect(url: string, token: string, onEvent: (...args: any[]) => any): Tunnel
  isConnected(): boolean
  /**
   * Promote this tunnel to server mode — installs the userspace
   * NAT that bridges client IP packets to host sockets. Idempotent
   * at call sites — fails if already in client or server mode.
   */
  startServer(): void
  /**
   * Hand the TUN fd over to the lktunnel core. The library takes
   * ownership: it spawns the TUN read loop on its dispatcher
   * thread and closes the fd on teardown. After this call the JS
   * side must NOT close the fd itself.
   */
  attachTun(fd: number): void
  /**
   * `[rx_pkts, rx_bytes, tx_pkts, tx_bytes]`. u32 is enough for
   * any realistic session (4 GB ≈ 4 billion packets / bytes); if
   * we ever need more we'll move to BigInt.
   */
  stats(): Array<number>
  /**
   * Tear down. Idempotent — safe to call multiple times. The
   * underlying `Drop` also fires teardown when the last JS
   * reference is collected, but explicit `disconnect()` is
   * recommended so the SFU sees the Leave promptly instead of
   * waiting out a ~30 s timeout.
   */
  disconnect(): void
}
export declare class TunGateway {
  /**
   * Take ownership of an open TUN fd (from `openTun`). Spawns the
   * shared read loop in a dedicated thread before returning.
   */
  static attach(fd: number): TunGateway
  /**
   * Reserve a SNAT lease for `tunnel` and install the gateway's
   * inbound-IP handler on it. Returns the lease octet (`2..254`)
   * — JS uses it only for logging / display, the actual rewrite
   * happens in Rust.
   */
  register(tunnel: Tunnel): number
  /**
   * Release the lease for `tunnel` and detach the gateway's
   * handler. Idempotent — calling twice or with an unregistered
   * tunnel is a no-op.
   */
  unregister(tunnel: Tunnel): void
  /**
   * Shut down the read thread and close the TUN fd. Idempotent.
   * After this the gateway is unusable; create a new one (with a
   * freshly-opened fd) to bring service back up.
   */
  close(): void
}
